# QM config schema - https://qm-docs.s3.amazonaws.com/v0.8/config/index.html
version: 1
controllers:
  con1:
    analog_outputs: {}
    analog_inputs: {}
elements:
  element_name:
    mixInputs:
      I: ~
      Q: ~
      lo_frequency: ~
      mixer: ~
    intermediate_frequency: ~
    operations: {}
    outputs:
      out1: ~
    time_of_flight: ~
    smearing: ~
mixers:
  mixer_name: [{
    intermediate_frequency: ~,
    lo_frequency: ~,
    correction: ~
  }]
pulses:
  pulse_name:
    operation: ~
    length: ~
    waveforms: 
      I: ~
      Q: ~
    integration_weights:
      weight_name: ~
    digital_marker: ~
waveforms:
  constant_wf:
    type: 'constant'
    sample: ~
  arbitrary_wf:
    type: 'arbitrary'
    samples: ~
    sampling_rate: 1
digital_waveforms:
  'ON': {'samples': ~}
integration_weights:
  weight_name:
    cosine: []
    sine: []
