# config of a typical quantum device with one qubit and one rr
---
!QuantumDevice
name: qdev
qubit: !QuantumElement
  name: qubit
  omega: ~
  lo_freq: 5.0e+9
  int_freq: 50.0e+6
  ports:
    I: 1
    Q: 2
  operations:
    CW: &CW_pulse !Pulse
      name: CW_pulse
      length: 60000
      waveforms:
        I: !ConstantWaveform
          name: constant_wf
          amp: 0.25
        Q: &zero_wf !ConstantWaveform
          name: zero_wf
          amp: 0.0
    gaussian: !Pulse
      name: gaussian_pulse
      length: 4000
      waveforms:
        I: !ArbitraryWaveform
          name: gauss_wf
          func: gauss_fn
          max_amp: 0.25
          sigma: 1000
          multiple_of_sigma: 4
        Q: *zero_wf
rr: !QuantumElement
  name: rr
  omega: ~
  lo_freq: 7.0e+9
  int_freq: -50.0e+6
  time_of_flight: 200
  smearing: 0
  ports:
    I: 3
    Q: 4
    out: 1
  operations:
    CW: *CW_pulse
    readout: !Pulse
      name: readout_pulse
      length: 800
      waveforms:
        I: !ConstantWaveform
          name: readout_wf
          amp: 0.32
        Q: *zero_wf
