# config of a set of control instruments
# each yaml doc (separated by ---) contains the spec for one instrument
---
!LabBrick
name: lb_qubit
serial_number: 25330
frequency: ~
power: 13
---
!LabBrick
name: lb_rr
serial_number: 25337
frequency: ~
power: 13
---
!Sa124
name: sa
serial_number: 19184645
center: ~
span: ~
rbw: 250.0e+3
ref_power: 0
#---
#!Opx
#name: con1
